# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci

language: haskell
sudo: enabled

cache:
  directories:
   - $HOME/.cabal/store

cabal: 2.4
ghc:
  - "8.6.4"
  - "8.4.4"
  - "8.2.2"
  - "8.0.2"
  - "7.10.3"
  - "7.8.4"
#  - "7.6.3"
#  - "7.4.2"
#  - "7.0.4"

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build all
#- cabal check
 - cabal v2-sdist all
