---
language: generic
dist: xenial
os: linux

cache:
  directories:
    - $HOME/.stack

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/TokTok/hs-tools/releases/download/v0.6/hs-tools-v0.6.tar.gz | tar xz -C $HOME

script:
  - hlint .
  - stylish-haskell-lhs -i .
  - git diff --exit-code
  - travis_wait stack --no-terminal test --coverage
  - shc msgpack-binary testsuite
